exclude: ["README.md", "config.ru", "Gemfile", "Gemfile.lock", "vendor"] # files to exclude

# Permalinks
permalink: pretty

# Setup
url: http://www.particle4dev.com

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl: ''

title: particle4dev

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description: >
  A geek, i ♡ containers, [Docker](https://www.docker.com), [Golang](https://golang.org), [Nodejs](https://nodejs.org/en).

# The tags listed as entries in the sidebar
sidebar_tags: [linux, docker, go, nodejs, devops, bitcoin-ethereum, others, life, graphql]
# sidebar_tags: []

# Fallback image and color if not overwritten for tag or post
image: /public/img/dark.jpg
color: '#A85641'

author:
  name: 'Hoang Nam'
  email: 'particle4dev@gmail.com'

  # Setting social media usernames will add icons at the bottom of the sidebar
  twitter: particle4dev
  github: particle4dev

  # Setting a disqus username will enable the comment section
  disqus: particle4dev

  # This photo will be used in the about section
  photo: /public/img/flo.jpg

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:          |
    Hoang Nam is a software engineer living in Ha Noi, Viet Nam.
    He does cloudy stuff with computers, currently for [CityMe](https://www.cityme.vn). He love open source projects as much as he loved his job.
    You can find him on twitter, where he is @particle4dev

kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true
