# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings
paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md", "config.ru", "Gemfile", "Gemfile.lock", "vendor"] # files to exclude
highlighter: pygments
markdown: kramdown

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: iojs vietnam community

name: iojs vietnam community
url: http://particle4dev.com/
baseurl: "" # the subpath of your site, e.g. /blog
description: iojs vietnam community Blog
author:
  name: particle4dev-blog
  email: particle4dev@gmail.com
  github: particle4dev
  twitter: particle4dev
  pinterest: particle4dev
  linkedin: particle4dev
  bio: Bringing ES6 to the Node Community in Vietnam!
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

gems:
- jekyll-sitemap

BASE_PATH: