exclude: ["README.md", "config.ru", "Gemfile", "Gemfile.lock", "vendor"] # files to exclude

# Permalinks
permalink: pretty

# Setup
url: http://www.particle4dev.com

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl: ''

title: Hydejack

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description: >
  A geek, i ♡ containers, [Docker](https://www.docker.com), [Golang](https://golang.org), [Nodejs](https://nodejs.org/en).
  
# The tags listed as entries in the sidebar
sidebar_tags: [jekyll, hyde]

# Fallback image and color if not overwritten for tag or post
image: /public/img/nap.jpg
color:            '#A85641'

author:
  name:           'Hoang Nam'

  # Setting social media usernames will add icons at the bottom of the sidebar
  twitter:        particle4dev
  github:         particle4dev

  # Setting a disqus username will enable the comment section
  disqus:         particle4dev

  # This photo will be used in the about section
  photo:          http://www.particle4dev.com/public/img/flo.jpg

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:          |
    Hi, I'm Hoang Nam or [`@particle4dev`](https://www.twitter.com/particle4dev), which isn't an acronym,
    I just [wanted a short username](http://particle4dev.com/how-to-find-a-short-username) and that one happened to be available.

    Read my thoughts on [#software](http://particle4dev.com/tag/software) and [#cryptoeconomics](http://qwtel.com/tag/cryptoeconomics).

kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true
